### ISSUE TITLE
Build of scipyserver often fails on Docker Hub

### ISSUE THREAD

**Issue by wielandbrendel** [wielandbrendel/agmb-docker#1]
The builds fail for two reasons: first, because of time-out (build > 2h) and because of

    Build process failed: The command '/bin/sh -c bash /tmp/build_scipy_stack.sh' returned a non-zero code: 1

Unfortunately, both errors are erratic and not reproducible at the moment. 90% of the time is spent in compiling Numpy and Scipy against OpenBLAS. But OpenBLAS is anyway only installed with interactive kernels, i.e. the kernels are chosen depending on the CPU of the host-system.

Is there a faster way to compile these packages, do we need them for Python 2 & 3 or are there any precompiled binaries with OpenBlas?

**Comment by matthias-k** [comment]
The `Build process failed` is probably not the actual error. What is the output of  `build_scipy_stack.sh`? The timeouts may be due to performance problems of dockerhub?

**Comment by wielandbrendel** [comment]
Indeed the timeouts are most likely due to performance problems: if less resources are available, then the build process takes longer and overshoots the maximum build time allowed.

Regarding the error, here is a more complete log (for even more details see e.g. [here](https://hub.docker.com/r/wielandbrendel/jupyter-scipyserver/builds/bkgfgeqjndciwxmtjh32z6l/))

    OpenBLAS build complete. (BLAS CBLAS LAPACK LAPACKE)
    
    OS               ... Linux             
    Architecture     ... x86_64               
    BINARY           ... 64bit                 
    C compiler       ... GCC  (command line : gcc)
    Fortran compiler ... GFORTRAN  (command line : gfortran)
    Library Name     ... libopenblasp-r0.2.15.a (Multi threaded; Max num-threads is 32)
   
    To install the library, you can run "make PREFIX=/path/to/your/installation install".
    
    [91m+ make install
    [0mmake -j 1 -f Makefile.install install
    make[1]: Entering directory `/tmp/build/OpenBLAS'
    Generating openblas_config.h in /opt/OpenBLAS/include
    Generating f77blas.h in /opt/OpenBLAS/include
    Generating cblas.h in /opt/OpenBLAS/include
    Copying LAPACKE header files to /opt/OpenBLAS/include
    Copying the static library to /opt/OpenBLAS/lib
    [91minstall: [0m[91mcannot stat ‘libopenblas-r0.2.15.a’[0m[91m: No such file or directory[0m[91m
    [0m[91mmake[1]: [0m[91m*** [install] Error 1[0m[91m
    [0mmake[1]: Leaving directory `/tmp/build/OpenBLAS'
    [91mmake: [0m[91m*** [install] Error 2[0m[91m
    [0mRemoving intermediate container 96cd4f9c5fef
    The command '/bin/sh -c bash /tmp/build_scipy_stack.sh' returned a non-zero code: 1

**Comment by matthias-k** [comment]
The install command tries to copy a `libopenblas-r0.2.15.a` but the build process produced a `libopenblasp-r0.2.15.a`. I guess you did not change anything in the OpenBLAS-part of the container? Otherwise I would assume a typo somewhere...

**Comment by wielandbrendel** [comment]
Well catched - but I didn't change anything on the side of OpenBLAS. We could try to build Numpy and Scipy against OpenBLAS and provide binary packages on Pypi. I cannot take a look now, but we might want to look into this.

**Comment by matthias-k** [comment]
I was able to build `wielandbrendel/jupyter-scipyserver` without any problems on my workstation. There, the library is called `libopenblasp-r0.2.15.a`. Thus it seems to be due to something in the dockerhub build system that leads to the install script looking for `libopenblas-r0.2.15.a`. Maybe something in OpenBLAS changed. We should look into the build scripts for OpenBLAS to understand this issue. I'll try to do this later.

**Comment by wielandbrendel** [comment]
Maybe we are not using the most up-to-date build script for OpenBLAS. I'll check that too. Just as a reminder: there is an option of continuosly building a binary package on [Anaconda Cloud](http://docs.anaconda.org/build.html). This way we might be able to build a binary package with OpenBLAS integration of Numpy and Scipy automatically - similar to how our Docker images are compiled on Docker Hub.

**Comment by matthias-k** [comment]
If we use the Anaconda Cloud, then we probably should think about using the anaconda python distribution as well, as the jupyter/scipy-notebook and jupyter/minimal-notebook ([Dockerfile](https://github.com/jupyter/docker-stacks/blob/master/minimal-notebook/Dockerfile)). This would immediatly give us precompiled numpy and scipy binaries (and as far as I know you can even get binaries compiled against MKL).

**Comment by wielandbrendel** [comment]
Not sure I am in favor of Anaconda Cloud. In particular it uses its own packaging system that seems to be incompatible with standard pip. Also, it feels too much enclosed in its own ecosystem.

I just check the recent build failures on Docker Hub and they are mostly about time-outs. I am starting to wonder whether we should simply stop supporting Python 2.7 or Python 3.4? This would cut the build time in half.

**Comment by wielandbrendel** [comment]
Or - as we just discussed - we split the jupyter-scipyserver in half and install Python 2 first, and then Python 3 second.

**Comment by wielandbrendel** [comment]
Sorry for the spam guys, but I wanted to test pull requests ;-). I'll merge this now and then make the appropriate changes to Docker Hub.

**Comment by wielandbrendel** [comment]
Since the splitting of the repositories the time-out errors seem to have vanished, but we still get a lot of these "no directory" errors. To track down the problem I created a minimum version of the Dockerfile (just Ubuntu 14.04 + OpenBLAS installation) and test the [build on Docker Hub](https://hub.docker.com/r/wielandbrendel/openblas-dockerhub-error-minimum-example/builds/) right now. Lets see how that goes.

**Comment by wielandbrendel** [comment]
The minimum example fails with the same error message (even more consistently then before). Also, another popular Ubuntu + OpenBLAS fails too, and so I filed an [issue](https://github.com/xianyi/OpenBLAS/issues/735) with the developers of OpenBLAS.

**Comment by wielandbrendel** [comment]
For the first time all builds from ldap-scipyserver until jupyter-deeplearning are running through! In IFTTT I set a rule to open a new Github Issue whenever a build on Docker Hub fails. Lets see if that works.
