### ISSUE TITLE
Update README to use agmb-docker script

### ISSUE THREAD

**Issue by jonasrauber** [wielandbrendel/agmb-docker#11]

**Comment by wielandbrendel** [comment]
Yep - the README is on my to-do list. I just want to see that the whole toolchain builds reliably on Docker Hub before writing the full documentation for each of the containers.

**Comment by wielandbrendel** [comment]
I updated the README and would appreciate someone to take a look whether I forgot any important information.

**Comment by jonasrauber** [comment]
see commit 34faacb19

**Comment by jonasrauber** [comment]
I think this issue can be closed

**Comment by jonasrauber** [comment]
Looks good, but the makefile might need some documentation in the README. Just a few examples how to use the different commands would be helpful.
