### ISSUE TITLE
RFC: bethgelab GitHub and Docker Hub organization

### ISSUE THREAD

**Issue by jonasrauber** [wielandbrendel/agmb-docker#39]
In light of the proposal to use individual repositories for each Docker image #40, it might make sense to collect all of them under a single GitHub organization [1] and a Docker Hub organization [2].

[1] https://github.com/blog/674-introducing-organizations
[2] https://docs.docker.com/docker-hub/orgs/

**Comment by wielandbrendel** [comment]
Sounds like a good idea - and would put our open-source code on a more professional level. What name should we choose? agmb, AGMB, AGBethge, AGbethge, bethgegroup, BethgeGroup?

**Comment by jonasrauber** [comment]
I propose *bethgelab*. After all, that's our domain name.

**Comment by jonasrauber** [comment]
I just saw that a bethgelab GitHub organization already exists, but it doesn't have public repositories or public members. So we should try to find out who has control over it.

**Comment by jonasrauber** [comment]
see https://github.com/bethgelab
and https://hub.docker.com/u/bethgelab/
