### ISSUE TITLE
Condense docker layers

### ISSUE THREAD

**Issue by matthias-k** [wielandbrendel/agmb-docker#44]
We should try to make the Dockerfiles more condensated. Right now, jupyter-deeplearning uses more than 120 of the allowed 127 layers. Right now I am running into problems adding another container on top of the deep learning container.

**Comment by jonasrauber** [comment]
started working on this at https://github.com/bethgelab/docker-jupyter-deeplearning

**Comment by jonasrauber** [comment]
`bethgelab/docker-jupyter-deeplearning` has only 89 layers now
@matthias-k please close if you successfully tried it out

**Comment by matthias-k** [comment]
Looks good to me, closing!
