### ISSUE TITLE
Jupyter 4.1

### ISSUE THREAD

**Issue by lukerogerson** [wielandbrendel/agmb-docker#7]
Could you update the Jupyter Notebooks to the latest edition? https://blog.jupyter.org/2016/01/08/notebook-4-1-release/

**Comment by wielandbrendel** [comment]
The jupyter notebook is built on master and is pretty recent (it also has multi-cell selection). But @matthias-k will built a job this afternoon to automatically update to the latest jupyter notebook. Check back in around two days on Docker Hub for the latest builds. Also, please note that things are in the flow right now, we'll need a couple of days to fix all the problems (see other issues).
