### ISSUE TITLE
Add Torch

### ISSUE THREAD

**Issue by wielandbrendel** [wielandbrendel/agmb-docker#9]
Jonas will contribute an install of Torch soon.

**Comment by wielandbrendel** [comment]
@jonasrauber I saw that there are binaries from NVIDIA for torch, as you can see in the install documentation of digits:

https://github.com/NVIDIA/DIGITS/blob/master/docs/BuildTorch.md

Any reason why we should not use those? Especially regarding compilation time this option would be very attractive.

**Comment by jonasrauber** [comment]
I will look into it.

**Comment by jonasrauber** [comment]
The following Dockerfile installs torch using the binaries from NVIDIA, but making it available in jupyter requires some extra work.

```
FROM wielandbrendel/jupyter-scipyserver-python2:cuda7.0-cudnn3

RUN apt-get update && apt-get install -y \
  wget

RUN CUDA_REPO_PKG=cuda-repo-ubuntu1404_7.5-18_amd64.deb && \
    wget http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1404/x86_64/$CUDA_REPO_PKG && \
    sudo dpkg -i $CUDA_REPO_PKG

RUN ML_REPO_PKG=nvidia-machine-learning-repo_4.0-2_amd64.deb && \
    wget http://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1404/x86_64/$ML_REPO_PKG && \
    sudo dpkg -i $ML_REPO_PKG

RUN apt-get update && apt-get install -y \
  torch7-nv
```
